sudo: required

services:
    - docker
    
script:
    - docker build -t mhanafy92/react-example:2 .
    - docker images mhanafy92/react-example:2

before_deploy:
    - docker login -u mhanafy92 -p mostapc

deploy:
    provider: script
    script: docker push mhanafy92/react-example:2
    on:
        branch: master